/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as LearnIndexImport } from './routes/learn/index'
import { Route as ConstructorIndexImport } from './routes/constructor/index'
import { Route as authSignupIndexImport } from './routes/(auth)/signup/index'
import { Route as authResetPasswordIndexImport } from './routes/(auth)/reset-password/index'
import { Route as authLoginIndexImport } from './routes/(auth)/login/index'
import { Route as authForgotPasswordIndexImport } from './routes/(auth)/forgot-password/index'
import { Route as authAuthCallbackIndexImport } from './routes/(auth)/auth/callback/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const LearnIndexRoute = LearnIndexImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRoute,
} as any)

const ConstructorIndexRoute = ConstructorIndexImport.update({
  id: '/constructor/',
  path: '/constructor/',
  getParentRoute: () => rootRoute,
} as any)

const authSignupIndexRoute = authSignupIndexImport.update({
  id: '/(auth)/signup/',
  path: '/signup/',
  getParentRoute: () => rootRoute,
} as any)

const authResetPasswordIndexRoute = authResetPasswordIndexImport.update({
  id: '/(auth)/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRoute,
} as any)

const authLoginIndexRoute = authLoginIndexImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const authForgotPasswordIndexRoute = authForgotPasswordIndexImport.update({
  id: '/(auth)/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRoute,
} as any)

const authAuthCallbackIndexRoute = authAuthCallbackIndexImport.update({
  id: '/(auth)/auth/callback/',
  path: '/auth/callback/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/constructor/': {
      id: '/constructor/'
      path: '/constructor'
      fullPath: '/constructor'
      preLoaderRoute: typeof ConstructorIndexImport
      parentRoute: typeof rootRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/forgot-password/': {
      id: '/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/reset-password/': {
      id: '/(auth)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signup/': {
      id: '/(auth)/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/auth/callback/': {
      id: '/(auth)/auth/callback/'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof authAuthCallbackIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/constructor': typeof ConstructorIndexRoute
  '/learn': typeof LearnIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/register': typeof RegisterIndexRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/login': typeof authLoginIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/auth/callback': typeof authAuthCallbackIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/constructor': typeof ConstructorIndexRoute
  '/learn': typeof LearnIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/register': typeof RegisterIndexRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/login': typeof authLoginIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/auth/callback': typeof authAuthCallbackIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/constructor/': typeof ConstructorIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/(auth)/forgot-password/': typeof authForgotPasswordIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/reset-password/': typeof authResetPasswordIndexRoute
  '/(auth)/signup/': typeof authSignupIndexRoute
  '/(auth)/auth/callback/': typeof authAuthCallbackIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/constructor'
    | '/learn'
    | '/profile'
    | '/register'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/constructor'
    | '/learn'
    | '/profile'
    | '/register'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/constructor/'
    | '/learn/'
    | '/profile/'
    | '/register/'
    | '/(auth)/forgot-password/'
    | '/(auth)/login/'
    | '/(auth)/reset-password/'
    | '/(auth)/signup/'
    | '/(auth)/auth/callback/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstructorIndexRoute: typeof ConstructorIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  authForgotPasswordIndexRoute: typeof authForgotPasswordIndexRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authResetPasswordIndexRoute: typeof authResetPasswordIndexRoute
  authSignupIndexRoute: typeof authSignupIndexRoute
  authAuthCallbackIndexRoute: typeof authAuthCallbackIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstructorIndexRoute: ConstructorIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  authForgotPasswordIndexRoute: authForgotPasswordIndexRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authResetPasswordIndexRoute: authResetPasswordIndexRoute,
  authSignupIndexRoute: authSignupIndexRoute,
  authAuthCallbackIndexRoute: authAuthCallbackIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/constructor/",
        "/learn/",
        "/profile/",
        "/register/",
        "/(auth)/forgot-password/",
        "/(auth)/login/",
        "/(auth)/reset-password/",
        "/(auth)/signup/",
        "/(auth)/auth/callback/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/constructor/": {
      "filePath": "constructor/index.tsx"
    },
    "/learn/": {
      "filePath": "learn/index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    },
    "/(auth)/forgot-password/": {
      "filePath": "(auth)/forgot-password/index.tsx"
    },
    "/(auth)/login/": {
      "filePath": "(auth)/login/index.tsx"
    },
    "/(auth)/reset-password/": {
      "filePath": "(auth)/reset-password/index.tsx"
    },
    "/(auth)/signup/": {
      "filePath": "(auth)/signup/index.tsx"
    },
    "/(auth)/auth/callback/": {
      "filePath": "(auth)/auth/callback/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
