/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as LessonImport } from './routes/lesson'
import { Route as LearnImport } from './routes/learn'
import { Route as ConstructorImport } from './routes/constructor'
import { Route as IndexImport } from './routes/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as authResetPasswordIndexImport } from './routes/(auth)/reset-password/index'
import { Route as authLoginIndexImport } from './routes/(auth)/login/index'
import { Route as authForgotPasswordIndexImport } from './routes/(auth)/forgot-password/index'
import { Route as authAuthCallbackIndexImport } from './routes/(auth)/auth/callback/index'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const LessonRoute = LessonImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => rootRoute,
} as any)

const LearnRoute = LearnImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRoute,
} as any)

const ConstructorRoute = ConstructorImport.update({
  id: '/constructor',
  path: '/constructor',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const authResetPasswordIndexRoute = authResetPasswordIndexImport.update({
  id: '/(auth)/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRoute,
} as any)

const authLoginIndexRoute = authLoginIndexImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const authForgotPasswordIndexRoute = authForgotPasswordIndexImport.update({
  id: '/(auth)/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRoute,
} as any)

const authAuthCallbackIndexRoute = authAuthCallbackIndexImport.update({
  id: '/(auth)/auth/callback/',
  path: '/auth/callback/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/constructor': {
      id: '/constructor'
      path: '/constructor'
      fullPath: '/constructor'
      preLoaderRoute: typeof ConstructorImport
      parentRoute: typeof rootRoute
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnImport
      parentRoute: typeof rootRoute
    }
    '/lesson': {
      id: '/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof LessonImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/forgot-password/': {
      id: '/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/reset-password/': {
      id: '/(auth)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/auth/callback/': {
      id: '/(auth)/auth/callback/'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof authAuthCallbackIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/constructor': typeof ConstructorRoute
  '/learn': typeof LearnRoute
  '/lesson': typeof LessonRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterIndexRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/login': typeof authLoginIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/auth/callback': typeof authAuthCallbackIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/constructor': typeof ConstructorRoute
  '/learn': typeof LearnRoute
  '/lesson': typeof LessonRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterIndexRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/login': typeof authLoginIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/auth/callback': typeof authAuthCallbackIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/constructor': typeof ConstructorRoute
  '/learn': typeof LearnRoute
  '/lesson': typeof LessonRoute
  '/profile': typeof ProfileRoute
  '/register/': typeof RegisterIndexRoute
  '/(auth)/forgot-password/': typeof authForgotPasswordIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/reset-password/': typeof authResetPasswordIndexRoute
  '/(auth)/auth/callback/': typeof authAuthCallbackIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/constructor'
    | '/learn'
    | '/lesson'
    | '/profile'
    | '/register'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/constructor'
    | '/learn'
    | '/lesson'
    | '/profile'
    | '/register'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/constructor'
    | '/learn'
    | '/lesson'
    | '/profile'
    | '/register/'
    | '/(auth)/forgot-password/'
    | '/(auth)/login/'
    | '/(auth)/reset-password/'
    | '/(auth)/auth/callback/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstructorRoute: typeof ConstructorRoute
  LearnRoute: typeof LearnRoute
  LessonRoute: typeof LessonRoute
  ProfileRoute: typeof ProfileRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  authForgotPasswordIndexRoute: typeof authForgotPasswordIndexRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authResetPasswordIndexRoute: typeof authResetPasswordIndexRoute
  authAuthCallbackIndexRoute: typeof authAuthCallbackIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstructorRoute: ConstructorRoute,
  LearnRoute: LearnRoute,
  LessonRoute: LessonRoute,
  ProfileRoute: ProfileRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  authForgotPasswordIndexRoute: authForgotPasswordIndexRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authResetPasswordIndexRoute: authResetPasswordIndexRoute,
  authAuthCallbackIndexRoute: authAuthCallbackIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/constructor",
        "/learn",
        "/lesson",
        "/profile",
        "/register/",
        "/(auth)/forgot-password/",
        "/(auth)/login/",
        "/(auth)/reset-password/",
        "/(auth)/auth/callback/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/constructor": {
      "filePath": "constructor.tsx"
    },
    "/learn": {
      "filePath": "learn.tsx"
    },
    "/lesson": {
      "filePath": "lesson.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    },
    "/(auth)/forgot-password/": {
      "filePath": "(auth)/forgot-password/index.tsx"
    },
    "/(auth)/login/": {
      "filePath": "(auth)/login/index.tsx"
    },
    "/(auth)/reset-password/": {
      "filePath": "(auth)/reset-password/index.tsx"
    },
    "/(auth)/auth/callback/": {
      "filePath": "(auth)/auth/callback/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
